apiVersion: v1
kind: Service
metadata:
  labels:
    app: workout-gateway
  name: workout-gateway
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: workout-gateway
  type: ClusterIP
