apiVersion: v1
kind: Service
metadata:
  labels:
    app: run-controller
  name: run-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: run-controller
  type: ClusterIP
